# Generated by Django 6.0.5 on 2026-05-07 17:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('documento', models.FileField(blank=True, null=True, upload_to='proyectos/', verbose_name='Documento PDF')),
                ('estado', models.CharField(choices=[('enviado', 'Enviado'), ('revision', 'En Revisión'), ('aprobado', 'Aprobado')], default='enviado', max_length=20, verbose_name='Estado')),
                ('fecha_envio', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de envío')),
                ('fecha_revision', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de revisión')),
                ('calificacion', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Calificación')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proyectos', to=settings.AUTH_USER_MODEL, verbose_name='Estudiante')),
            ],
            options={
                'verbose_name': 'Proyecto',
                'verbose_name_plural': 'Proyectos',
                'ordering': ['-fecha_envio'],
            },
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField(verbose_name='Comentario')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='Fecha')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='Ejercicio2App.proyecto', verbose_name='Proyecto')),
            ],
            options={
                'verbose_name': 'Comentario',
                'verbose_name_plural': 'Comentarios',
                'ordering': ['fecha'],
            },
        ),
    ]
